In [129]:
import pyscf

import itertools

import numpy as np
import scipy as sp

import math
import itertools

from copy import deepcopy

def dci_bruteforce(h1e = np.load("h1e.npy"), 
                   h2e = np.load("h2e.npy"), norb = 6, nelec = 6):
    
    nalpha = nelec // 2
    nbeta = nelec - nalpha

    spinless_determinants = list(itertools.combinations(range(norb), nalpha))
    # print(spinless_determinants)
    editable_spinless_determinants = [list(x) for x in spinless_determinants]

    # spinned_determinants_ppar = []
    # for i in range(len(spinless_determinants)):
    #     for j in range(len(spinless_determinants)):
    #         spinned_determinants_ppar.append((spinless_determinants[i], spinless_determinants[j]))

    # spinned_determinants_barpar = [list(x) for x in spinned_determinants_ppar]

    spinned_determinants_parbar = []
    for i in range(len(spinless_determinants)):
        for j in range(len(spinless_determinants)):
          spinned_determinants_parbar.append((editable_spinless_determinants[i], editable_spinless_determinants[j]))
    
    spinned_determinants_bbar = [list(x) for x in spinned_determinants_parbar]

    # spinless_eij

    def spinless_f(spinless_index, i, j):
        spinless_det = deepcopy(editable_spinless_determinants[spinless_index])
        if j not in spinless_det:
            return None
        else:
            spinless_det.remove(j)
            if i in spinless_det:
                return None
            else:
                spinless_det.append(i)
                spinless_det = sorted(spinless_det)
                spinless_det = tuple(spinless_det)
                output_spinless_index = spinless_determinants.index(spinless_det)
                return output_spinless_index

    def spinless_sigma(spinless_index, i, j):
        spinless_det = deepcopy(editable_spinless_determinants[spinless_index])
        # print("Indexed det: ", spinless_det)
        if j not in spinless_det:
            return None
        else:
            # spinless_det.remove(j)
            jindex = spinless_det.index(j)
            copy_spinless_det = deepcopy(spinless_det)
            copy_spinless_det.remove(j)
            if i in copy_spinless_det:
                return None
            else:
                spinless_det[jindex] = i
                # print("Updated det: ", spinless_det)
                sorted_spinless_det = sorted(spinless_det)
                # print("Sorted det: ", sorted_spinless_det)
                swaps = 0
                while sorted_spinless_det != spinless_det:
                    for k in range(len(spinless_det) - 1):
                        if spinless_det[k] > spinless_det[k+1]:
                            termi = spinless_det[k]
                            terminext = spinless_det[k+1]
                            spinless_det[k] = terminext
                            spinless_det[k+1] = termi
                            # print("Sort result: ", spinless_det)
                            swaps += 1
                # print(swaps)    
                return swaps
    
    def spinless_eij(spinless_index, i, j):
        f_result = spinless_f(spinless_index, i, j)
        if f_result is None:
            return None
        else:
            sigma_result = spinless_sigma(spinless_index, i, j)
            return (f_result, (-1)**sigma_result)
    
    spinless_eij_dict = {}
    def make_spinless_eij():
        for i in range(norb):
            for j in range(norb):
                for index in range(len(editable_spinless_determinants)):
                    eij = spinless_eij(index, i, j)
                    if eij is not None:
                        if index not in spinless_eij_dict:
                            spinless_eij_dict[index] = {}
                        spinless_eij_dict[index][(i, j)] = eij
    make_spinless_eij()

    def alpha_Eij(spinned_index, i, j):
        term = spinned_determinants_bbar[spinned_index]
        term_alpha = term[0]
        term_beta = term[1]
        
        # need to get alpha index in spinless determinants.
        alpha_index = editable_spinless_determinants.index(term_alpha)
        try:
            spinless_alpha_output = spinless_eij_dict[alpha_index][(i,j)]
        except:
            spinless_alpha_output = None
            return None
        
        if spinless_alpha_output is not None:
            new_term_alpha = editable_spinless_determinants[spinless_alpha_output[0]]
            new_term = [new_term_alpha, term_beta]
            new_index = spinned_determinants_bbar.index(new_term)
            return (new_index, spinless_alpha_output[1])
    
    def beta_Eij(spinned_index, i, j):
        term = spinned_determinants_bbar[spinned_index]
        term_alpha = term[0]
        term_beta = term[1]

        beta_index = editable_spinless_determinants.index(term_beta)
        try:
            spinless_beta_output = spinless_eij_dict[beta_index][(i,j)]
        except:
            spinless_beta_output = None
            return None
        
        if spinless_beta_output is not None:
            new_term_beta = editable_spinless_determinants[spinless_beta_output[0]]
            new_term = [term_alpha, new_term_beta]
            new_index = spinned_determinants_bbar.index(new_term)
            return (new_index, spinless_beta_output[1])
        

    alpha_Eij_dict = {}
    beta_Eij_dict = {}
    
    def make_alpha_Eij():
        for i in range(norb):
            for j in range(norb):
                for index in range(len(spinned_determinants_bbar)):
                    
                    Eij_alpha = alpha_Eij(index, i, j)
                    if Eij_alpha is not None:
                        if index not in alpha_Eij_dict:
                            alpha_Eij_dict[index] = {}
                        alpha_Eij_dict[index][(i,j)] = Eij_alpha

    def make_beta_Eij():
        for i in range(norb):
            for j in range(norb):
                for index in range(len(spinned_determinants_bbar)):
                    
                    Eij_beta = beta_Eij(index, i, j)
                    if Eij_beta is not None:
                        if index not in beta_Eij_dict:
                            beta_Eij_dict[index] = {}
                        beta_Eij_dict[index][(i,j)] = Eij_beta
    
    make_alpha_Eij()
    make_beta_Eij()


    dimension = len(spinned_determinants_bbar)

    print(dimension)
    hamiltonian_matrix = np.zeros((dimension,dimension))
    print(hamiltonian_matrix)


    def h_oneEl(h1e, h2e, alpha_dict = alpha_Eij_dict, beta_dict = beta_Eij_dict):
        gijjk = np.einsum('pqqr->pr', h2e)
        for init_index in range(dimension):
            for (i,j) in alpha_dict[init_index]:
                output_index, sign = alpha_dict[init_index][(i,j)]
                # print(output_index, sign)
                hamiltonian_matrix[init_index, output_index] += h1e[i,j] * sign
                hamiltonian_matrix[init_index, output_index] -= 0.5*gijjk[i,j] * sign
            for (i,j) in beta_dict[init_index]:
                output_index, sign = beta_dict[init_index][(i,j)]
                hamiltonian_matrix[init_index, output_index] += h1e[i,j] * sign
                hamiltonian_matrix[init_index, output_index] -= 0.5*gijjk[i,j] * sign
    
    h_oneEl(h1e, h2e)

    def h_twoEl_coulomb(h2e, alpha_dict = alpha_Eij_dict, beta_dict = beta_Eij_dict):
        # do alpha alpha terms first:
        for init_index in range(dimension):
            # need to do g_iljk E_il E_jk --> do E_jk first
            for (j,k) in alpha_dict[init_index]:
                intermediate_index, intermediate_sign = alpha_dict[init_index][(j,k)]
                for (i,l) in alpha_dict[intermediate_index]:
                    output_index, sign = alpha_dict[intermediate_index][(i,l)]
                    hamiltonian_matrix[output_index, init_index] += 0.5*h2e[i,l,j,k] * intermediate_sign * sign
                for (i,l) in beta_dict[intermediate_index]:
                    output_index, sign = beta_dict[intermediate_index][(i,l)]
                    hamiltonian_matrix[output_index, init_index] += 0.5* h2e[i,l,j,k] * intermediate_sign * sign

            for (j,k) in beta_dict[init_index]:
                intermediate_index, intermediate_sign = beta_dict[init_index][(j,k)]
                for (i,l) in alpha_dict[intermediate_index]:
                    output_index, sign = alpha_dict[intermediate_index][(i,l)]
                    hamiltonian_matrix[output_index, init_index] += 0.5* h2e[i,l,j,k] * intermediate_sign * sign
                for (i,l) in beta_dict[intermediate_index]:
                    output_index, sign = beta_dict[intermediate_index][(i,l)]
                    hamiltonian_matrix[output_index, init_index] += 0.5*h2e[i,l,j,k] * intermediate_sign * sign

    h_twoEl_coulomb(h2e)


    return hamiltonian_matrix
                    

hammy = dci_bruteforce()    

                    



        
        

    


400
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [131]:
np.linalg.eigh(hammy)[0][0]

-7.839908014896353

In [ ]:
def h_oneEl(alphadict, betadict, h1emat = np.load(), h2emat)

In [89]:
norb = 6
nalpha = 3

spinless_determinants = list(itertools.combinations(range(norb), nalpha))
editable_spinless_determinants = [list(x) for x in spinless_determinants]
print("Editable spinless determinants", editable_spinless_determinants)


    # spinless_determinants = list(itertools.combinations(range(norb), nalpha))
    # editable_spinless_determinants = [list(x) for x in spinless_determinants]

spinned_determinants = []
for i in range(len(editable_spinless_determinants)):
    for j in range(len(editable_spinless_determinants)):
        spinned_determinants.append((editable_spinless_determinants[i], editable_spinless_determinants[j]))

# print(spinned_determinants)

editable_spinned_determinants = [list(x) for x in spinned_determinants]


spinned_determinants_bbar = deepcopy(editable_spinned_determinants)
print("Spinned determinants bbar: ", spinned_determinants_bbar)

def spinless_f(spinless_index, i, j):
    spinless_det = deepcopy(editable_spinless_determinants[spinless_index])
    if j not in spinless_det:
        return None
    else:
        spinless_det.remove(j)
        if i in spinless_det:
            return None
        else:
            spinless_det.append(i)
            spinless_det = sorted(spinless_det)
            spinless_det = tuple(spinless_det)
            output_spinless_index = spinless_determinants.index(spinless_det)
            return output_spinless_index
        
# def spinless_sigma(spinless_index, i, j):
#     spinless_det = deepcopy(editable_spinless_determinants[spinless_index])
#     if j not in spinless_det:
#         return None
#     else:
#         spinless_det.remove(j)
#         if i in spinless_det:
#             return None
#         else:
#             spinless_det.append(i)
#             sorted_spinless_det = sorted(spinless_det)
#             swaps = 0
#             while sorted_spinless_det != spinless_det:
#                 for i in range(len(spinless_det) - 1):
#                     if spinless_det[i] > spinless_det[i+1]:
#                         termi = spinless_det[i]
#                         terminext = spinless_det[i+1]
#                         spinless_det[i] = terminext
#                         spinless_det[i+1] = termi
#                         swaps += 1
                
#             return swaps

def spinless_sigma(spinless_index, i, j):
    spinless_det = deepcopy(editable_spinless_determinants[spinless_index])
    # print("Indexed det: ", spinless_det)
    if j not in spinless_det:
        return None
    else:
        # spinless_det.remove(j)
        jindex = spinless_det.index(j)
        copy_spinless_det = deepcopy(spinless_det)
        copy_spinless_det.remove(j)
        if i in copy_spinless_det:
            return None
        else:
            spinless_det[jindex] = i
            # print("Updated det: ", spinless_det)
            sorted_spinless_det = sorted(spinless_det)
            # print("Sorted det: ", sorted_spinless_det)
            swaps = 0
            while sorted_spinless_det != spinless_det:
                for k in range(len(spinless_det) - 1):
                    if spinless_det[k] > spinless_det[k+1]:
                        termi = spinless_det[k]
                        terminext = spinless_det[k+1]
                        spinless_det[k] = terminext
                        spinless_det[k+1] = termi
                        # print("Sort result: ", spinless_det)
                        swaps += 1
            # print(swaps)    
            return swaps

def spinless_eij(spinless_index, i, j):
    f_result = spinless_f(spinless_index, i, j)
    if f_result is None:
        return None
    else:
        sigma_result = spinless_sigma(spinless_index, i, j)
        return (f_result, (-1)**sigma_result)

spinless_eij_dict = {}
def make_spinless_eij():
    for i in range(norb):
        for j in range(norb):
            for index in range(len(editable_spinless_determinants)):
                eij = spinless_eij(index, i, j)
                if eij is not None:
                    if index not in spinless_eij_dict:
                        spinless_eij_dict[index] = {}
                    spinless_eij_dict[index][(i, j)] = eij


make_spinless_eij()

# print(spinless_eij_dict[0])
# for (i,j), (value,sign) in spinless_eij_dict[0].items():
#     print(f"E({i},{j}): {value}")
#     print(spinless_determinants[0], "\t-->", sign, "\t",spinless_determinants[np.abs(value)])
#     print()


def alpha_Eij(spinned_index, i, j):
    term = spinned_determinants_bbar[spinned_index]
    print(term)
    term_alpha = term[0]
    print("Alpha: ", term_alpha)
    term_beta = term[1]
    # print(term_beta)
    
    # need to get alpha index in spinless determinants.
    alpha_index = editable_spinless_determinants.index(term_alpha)
    print(alpha_index)
    try:
        spinless_alpha_output = spinless_eij_dict[alpha_index][(i,j)]
        print(spinless_alpha_output)
    except:
        spinless_alpha_output = None
        return None
    
    if spinless_alpha_output is not None:
        new_term_alpha = editable_spinless_determinants[spinless_alpha_output[0]]
        print(new_term_alpha)
        new_term = [new_term_alpha, term_beta]
        print(new_term)
        new_index = spinned_determinants_bbar.index(new_term)
        print(new_index)
        print(spinned_determinants_bbar[new_index])
        return (new_index, spinless_alpha_output[1])

# print("Remove 0, Add 0")
# print(alpha_Eij(1, 0, 0))


def beta_Eij(spinned_index, i, j):
    term = spinned_determinants_bbar[spinned_index]
    term_alpha = term[0]
    term_beta = term[1]

    beta_index = editable_spinless_determinants.index(term_beta)
    try:
        spinless_beta_output = spinless_eij_dict[beta_index][(i,j)]
    except:
        spinless_beta_output = None
        return None
    
    if spinless_beta_output is not None:
        new_term_beta = editable_spinless_determinants[spinless_beta_output[0]]
        new_term = [term_alpha, new_term_beta]
        new_index = spinned_determinants_bbar.index(new_term)
        return (new_index, spinless_beta_output[1])



alpha_Eij_dict = {}
beta_Eij_dict = {}

def make_alpha_Eij():
    for i in range(norb):
        for j in range(norb):
            for index in range(len(spinned_determinants_bbar)):
                
                Eij_alpha = alpha_Eij(index, i, j)
                if Eij_alpha is not None:
                    if index not in alpha_Eij_dict:
                        alpha_Eij_dict[index] = {}
                    alpha_Eij_dict[index][(i,j)] = Eij_alpha

def make_beta_Eij():
    for i in range(norb):
        for j in range(norb):
            for index in range(len(spinned_determinants_bbar)):
                
                Eij_beta = beta_Eij(index, i, j)
                if Eij_beta is not None:
                    if index not in beta_Eij_dict:
                        beta_Eij_dict[index] = {}
                    beta_Eij_dict[index][(i,j)] = Eij_beta

make_alpha_Eij()
make_beta_Eij()


Editable spinless determinants [[0, 1, 2], [0, 1, 3], [0, 1, 4], [0, 1, 5], [0, 2, 3], [0, 2, 4], [0, 2, 5], [0, 3, 4], [0, 3, 5], [0, 4, 5], [1, 2, 3], [1, 2, 4], [1, 2, 5], [1, 3, 4], [1, 3, 5], [1, 4, 5], [2, 3, 4], [2, 3, 5], [2, 4, 5], [3, 4, 5]]
Spinned determinants bbar:  [[[0, 1, 2], [0, 1, 2]], [[0, 1, 2], [0, 1, 3]], [[0, 1, 2], [0, 1, 4]], [[0, 1, 2], [0, 1, 5]], [[0, 1, 2], [0, 2, 3]], [[0, 1, 2], [0, 2, 4]], [[0, 1, 2], [0, 2, 5]], [[0, 1, 2], [0, 3, 4]], [[0, 1, 2], [0, 3, 5]], [[0, 1, 2], [0, 4, 5]], [[0, 1, 2], [1, 2, 3]], [[0, 1, 2], [1, 2, 4]], [[0, 1, 2], [1, 2, 5]], [[0, 1, 2], [1, 3, 4]], [[0, 1, 2], [1, 3, 5]], [[0, 1, 2], [1, 4, 5]], [[0, 1, 2], [2, 3, 4]], [[0, 1, 2], [2, 3, 5]], [[0, 1, 2], [2, 4, 5]], [[0, 1, 2], [3, 4, 5]], [[0, 1, 3], [0, 1, 2]], [[0, 1, 3], [0, 1, 3]], [[0, 1, 3], [0, 1, 4]], [[0, 1, 3], [0, 1, 5]], [[0, 1, 3], [0, 2, 3]], [[0, 1, 3], [0, 2, 4]], [[0, 1, 3], [0, 2, 5]], [[0, 1, 3], [0, 3, 4]], [[0, 1, 3], [0, 3, 5]], [[0, 1, 3], [0, 4, 5]],

In [99]:
#### testing dictionaries

def test_alpha_dict(someindex, creation, annihilation):
    alpha_output = alpha_Eij_dict[someindex][(creation,annihilation)]
    init_det = spinned_determinants_bbar[someindex]
    final_det = spinned_determinants_bbar[alpha_output[0]]
    sign = alpha_output[1]
    print(
        "Initial: ", init_det,
        "\n Final: ", final_det,
        "\n Sign: ", sign
    )

def test_beta_dict(someindex, creation, annihilation):
    beta_output = beta_Eij_dict[someindex][(creation,annihilation)]
    init_det = spinned_determinants_bbar[someindex]
    final_det = spinned_determinants_bbar[beta_output[0]]
    sign = beta_output[1]
    print(
        "Initial: ", init_det,
        "\n Final: ", final_det,
        "\n Sign: ", sign
    )

In [104]:
print(spinned_determinants_bbar[0])
for (tag1, tag2) in alpha_Eij_dict[0]:
    print(tag1, tag2)

[[0, 1, 2], [0, 1, 2]]
0 0
1 1
2 2
3 0
3 1
3 2
4 0
4 1
4 2
5 0
5 1
5 2


In [100]:
test_alpha_dict(5, 3, 1)
test_beta_dict(5, 3, 2)

Initial:  [[0, 1, 2], [0, 2, 4]] 
 Final:  [[0, 2, 3], [0, 2, 4]] 
 Sign:  -1
Initial:  [[0, 1, 2], [0, 2, 4]] 
 Final:  [[0, 1, 2], [0, 3, 4]] 
 Sign:  1


In [29]:
spinless_det = [1, 2, 3, 4]
modspinless = spinless_det.remove(2)  # Removes 2 from spinless_det

print(spinless_det)  # Output: [1, 3, 4] (modified!)
print(modspinless)    # Output: None (return value of .remove())

[1, 3, 4]
None


In [27]:
spinless_sigma(5, 1, 4)

Indexed det:  [0, 2, 4]
Updated det:  [0, 2, 1]
Sorted det:  [0, 1, 2]
Sort result:  [0, 1, 2]
1


1

In [10]:
print(editable_spinless_determinants)

[[0, 1, 2], [0, 1, 3], [0, 1, 4], [0, 1, 5], [0, 2, 3], [0, 2, 4], [0, 2, 5], [0, 3, 4], [0, 3, 5], [0, 4, 5], [1, 2, 3], [1, 2, 4], [1, 2, 5], [1, 3, 4], [1, 3, 5], [1, 4, 5], [2, 3, 4], [2, 3, 5], [2, 4, 5], [3, 4, 5]]
